<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-30T14:15:47Z" name="Default suite" finished-at="2023-01-30T14:15:47Z" duration-ms="39">
    <groups>
    </groups>
    <test started-at="2023-01-30T14:15:47Z" name="Default test" finished-at="2023-01-30T14:15:47Z" duration-ms="39">
      <class name="testcase.CasosCarrito">
        <test-method is-config="true" signature="abrirNavegador()[pri:0, instance:testcase.CasosCarrito@4d2a1da3]" started-at="2023-01-30T11:15:45Z" name="abrirNavegador" finished-at="2023-01-30T11:15:47Z" duration-ms="2099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- abrirNavegador -->
        <test-method signature="elegirArticulosAzarCarritoCompras()[pri:0, instance:testcase.CasosCarrito@4d2a1da3]" started-at="2023-01-30T11:15:47Z" name="elegirArticulosAzarCarritoCompras" finished-at="2023-01-30T11:15:47Z" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Store] but found [Account Suspended]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Store] but found [Account Suspended]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at testcase.CasosCarrito.elegirArticulosAzarCarritoCompras(CasosCarrito.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elegirArticulosAzarCarritoCompras -->
        <test-method is-config="true" signature="cerrarNavegador()[pri:0, instance:testcase.CasosCarrito@4d2a1da3]" started-at="2023-01-30T11:15:47Z" name="cerrarNavegador" finished-at="2023-01-30T11:15:47Z" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cerrarNavegador -->
      </class> <!-- testcase.CasosCarrito -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
